### ISSUE TITLE
Wrong modulatoin timing

### ISSUE THREAD

**Issue by kd-chicago** [MajicDesigns/MD_multiCameraIrControl#1]
'New' version does not work with Olympus E510/E520 cameras. The reason is 'new' version modulation frequency is too low.
'new' version uses 'wait' procedure trying to create required 38.4kHz modulation:
`while (micros() - start <= time)
  {
    digitalWrite(_pin, HIGH);
    wait(pause);
    digitalWrite(_pin, LOW);
    wait(pause);
  } 
`
the 'original' code has this procedure defined as well, but it creates modulation frequency  using delayMicroseconds:
`  while(micros()-start<=time){
    digitalWrite(pinLED,HIGH);
    delayMicroseconds(pause);
    digitalWrite(pinLED,LOW);
    delayMicroseconds(pause);
  }`

As a result, single pulse width of the original code is 12us, while the new implementation generates 18us pulses:
'new' code 9ms leading pulse burst:
https://imgur.com/HBk93sM
'original' code leading burst:
https://imgur.com/64HSDvF

for testing purpose I modified MD_multiCameraIrControl.cpp file:

`void cCamera::high(uint32_t time)
{
  uint32_t pause = (1000 / _freq / 2) - 4;
  uint32_t start = micros();

  while (micros() - start <= time)
  {
    digitalWrite(_pin, HIGH);
//    wait(pause);
    delayMicroseconds(pause);
    digitalWrite(_pin, LOW);
//    wait(pause);
    delayMicroseconds(pause);
  }
}`

After that modification pulse length changed to 12.8us, and now E5.shutterNow() successfully initiates a shot:
https://imgur.com/n1jsBq2

**Comment by MajicDesigns** [comment]
Thanks for testing with the Olympus. I'll modify the library and reissue as the next version up.

**Comment by kd-chicago** [comment]
Hey, it looks like you messed up with that update. Now it doesn't even
compile.
You removed 'wait' definition from .h file, but it is still used in .cpp.

**Comment by MajicDesigns** [comment]
Yup. I did. Will fix and reissue same version.

**Comment by kd-chicago** [comment]
Tested on Olympus E-520, now it works.
Just FYI - my implementation of IR Remote, code below:
(why? I need external monitor for controlling viewfinder output and shutter
remote at the same time.
E520 has both wired remote and AV output through single USB terminal, so
normally one can connect either AV or remote.
So I have monitor connected to AV USB and my 'wired' IR remote attached to
the front IR sensor and controlled by remote button.
Yes, I know there is an option
<https://www.ahfairley.com/Tutorials/E520Cable/Tutorial.htm> of making
double cable combining AV and remote, I am just too lazy for that)
Remote case - just a storage box
<https://www.buddyrc.com/cdn/shop/products/CASE-18650-CL__11682.jpg?v=1624871442>
from two 18650 batteries
AVR arduino-like
<https://www.openhardware.io/view/85/devDuino-Sensor-Node-V22-ATmega-328> -
it came with batteries holder and compact enough:)
https://imgur.com/fT0Gvj2
https://imgur.com/ax3cO5D
https://imgur.com/HImlaZC

`/************************************************************
* WHEN: 29-OCT-2023
* WHAT: IR Remote for Olympus E-520/510
* DETAILS:  
* Based on 
* https://github.com/dharmapurikar/Arduino/tree/master/libraries/multiCameraIrControl
* and  
* https://github.com/MajicDesigns/MD_multiCameraIrControl
* uses pushbutton on D5
*/
#include <ezButton.h>
#include <MD_multiCameraIrControl.h>
#define IR_LED 4
#define LED 9

const int buttonPin = 5; 
ezButton button(5);
Olympus E5(4);

void setup() {
    Serial.begin(115200);
    while (!Serial)    
    Serial.print("Sketch:   ");   Serial.println(__FILE__);
    Serial.print("Uploaded: ");   Serial.println(__DATE__);
    pinMode(IR_LED, OUTPUT);
    pinMode(LED, OUTPUT);
    pinMode(buttonPin, INPUT_PULLUP);    
    digitalWrite(LED, HIGH);
};

void loop() {
  button.loop();
  if (button.isPressed()) {
      E5.shutterNow();
      digitalWrite(LED, LOW);
      delay(2000);
      digitalWrite(LED, HIGH);      
    } 
};`

**Comment by kd-chicago** [comment]
`/************************************************************
* WHEN: 29-OCT-2023
* WHAT: IR Remote for Olympus E-520/510
* DETAILS:  
* Based on 
* https://github.com/dharmapurikar/Arduino/tree/master/libraries/multiCameraIrControl
* and  
* https://github.com/MajicDesigns/MD_multiCameraIrControl
* uses pushbutton on D5
*/
#include <ezButton.h>
#include <MD_multiCameraIrControl.h>
#define IR_LED 4
#define LED 9

const int buttonPin = 5; 
ezButton button(5);
Olympus E5(4);

void setup() {
    Serial.begin(115200);
    while (!Serial)    
    Serial.print("Sketch:   ");   Serial.println(__FILE__);
    Serial.print("Uploaded: ");   Serial.println(__DATE__);
    pinMode(IR_LED, OUTPUT);
    pinMode(LED, OUTPUT);
    pinMode(buttonPin, INPUT_PULLUP);    
    digitalWrite(LED, HIGH);
};

void loop() {
  button.loop();
  if (button.isPressed()) {
      E5.shutterNow();
      digitalWrite(LED, LOW);
      delay(2000);
      digitalWrite(LED, HIGH);      
    } 
};`
